import json
import os
from google import genai
from google.genai import types
import nflreadpy as nfl
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
import xgboost as xgb

# 1. Environment & API setup
db_url = os.environ.get("DATABASE_URL")
gemini_key = os.environ.get("GEMINI_API_KEY")

if not db_url or not gemini_key:
  raise ValueError("Missing DATABASE_URL or GEMINI_API_KEY in environment.")

engine = create_engine(db_url)
client = genai.Client(api_key=gemini_key)

# 2. Load trained XGBoost model
MODEL_FILE = "nfl_model.json"
model = xgb.XGBClassifier()
if os.path.exists(MODEL_FILE):
  model.load_model(MODEL_FILE)
  print("Loaded nfl_model.json successfully.")
else:
  raise FileNotFoundError(
      f"Model file {MODEL_FILE} not found in root directory."
  )

# 3. Pull recent play-by-play for rolling feature engineering
print("Calculating current rolling EPA metrics...")
current_season = 2026
pbp = nfl.load_pbp(seasons=[current_season]).to_pandas()
schedules = nfl.load_schedules(seasons=[current_season]).to_pandas()

# Filter regular pass/run plays
pbp_clean = pbp[pbp["play_type"].isin(["pass", "run"])].copy()

if not pbp_clean.empty:
  team_stats = (
      pbp_clean.groupby(["week", "posteam"])
      .agg(off_epa=("epa", "mean"), succ_rate=("success", "mean"))
      .reset_index()
      .rename(columns={"posteam": "team"})
  )

  # Compute strictly lagged rolling metrics
  team_stats.sort_values(["team", "week"], inplace=True)
  team_stats["roll_off_epa"] = team_stats.groupby("team")["off_epa"].transform(
      lambda x: x.shift(1).ewm(span=4, min_periods=1).mean()
  )
  team_stats["roll_succ_rate"] = team_stats.groupby("team")[
      "succ_rate"
  ].transform(lambda x: x.shift(1).ewm(span=4, min_periods=1).mean())
else:
  team_stats = pd.DataFrame(
      columns=["week", "team", "roll_off_epa", "roll_succ_rate"]
  )

# 4. Target upcoming unplayed matchups
upcoming = schedules[schedules["result"].isna()].head(3).copy()

system_prompt = (
    "You are a quantitative NFL analyst. You will receive market lines "
    "along with win probabilities generated by a proprietary XGBoost model "
    "trained on rolling EPA/play differentials. Synthesize the statistical model "
    "output with matchup context. Return a structured breakdown:\n"
    "1. Model Edge (Compare model probability to spread/moneyline)\n"
    "2. Key Mismatch\n"
    "3. Value Lean"
)

records = []
for _, game in upcoming.iterrows():
  home_team = game["home_team"]
  away_team = game["away_team"]
  matchup = f"{away_team} @ {home_team}"
  week_num = int(game["week"]) if pd.notna(game["week"]) else 1

  # Extract rolling features for home and away
  home_metrics = team_stats[
      (team_stats["team"] == home_team) & (team_stats["week"] == week_num)
  ]
  away_metrics = team_stats[
      (team_stats["team"] == away_team) & (team_stats["week"] == week_num)
  ]

  home_epa = (
      home_metrics["roll_off_epa"].values[0] if not home_metrics.empty else 0.0
  )
  home_succ = (
      home_metrics["roll_succ_rate"].values[0]
      if not home_metrics.empty
      else 0.45
  )
  away_epa = (
      away_metrics["roll_off_epa"].values[0] if not away_metrics.empty else 0.0
  )
  away_succ = (
      away_metrics["roll_succ_rate"].values[0]
      if not away_metrics.empty
      else 0.45
  )

  diff_epa = float(home_epa - away_epa)
  diff_succ = float(home_succ - away_succ)

  # Run XGBoost inference
  feature_input = pd.DataFrame(
      [[diff_epa, diff_succ]], columns=["diff_epa", "diff_succ"]
  )
  home_win_prob = float(model.predict_proba(feature_input)[0][1])

  print(f"Matchup: {matchup} | Model Home Win Prob: {home_win_prob:.1%}")

  payload = {
      "matchup": matchup,
      "week": week_num,
      "spread_line": (
          float(game["spread_line"]) if pd.notna(game["spread_line"]) else 0.0
      ),
      "total_line": (
          float(game["total_line"]) if pd.notna(game["total_line"]) else 0.0
      ),
      "model_metrics": {
          "home_team": home_team,
          "home_win_probability": f"{home_win_prob:.1%}",
          "away_win_probability": f"{(1 - home_win_prob):.1%}",
          "epa_differential": round(diff_epa, 4),
          "success_rate_differential": round(diff_succ, 4),
      },
  }

  response = client.models.generate_content(
      model="gemini-3.6-flash",
      contents=json.dumps(payload),
      config=types.GenerateContentConfig(
          system_instruction=system_prompt, temperature=0.2
      ),
  )

  records.append({
      "game_id": str(game["game_id"]),
      "week": week_num,
      "matchup": matchup,
      "home_win_prob": home_win_prob,
      "analysis": response.text,
  })

# 5. Overwrite/Insert into Neon DB
if records:
  df_results = pd.DataFrame(records)
  # Writes results directly to your Neon table
  df_results.to_sql(
      "nfl_weekly_analysis", engine, if_exists="append", index=False
  )
  print("Neon database updated with model-backed predictions.")
